# Deploy AzDO VSTS Agent Pods to an AKS cluster
# Replace anything within {} with your own values

resources:
- repo: self
  clean: true
queue:
  name: Hosted Ubuntu 1604
trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - '{PATH_TO_TERRAFORM_DIR}'
variables:
- name: AKS_SUBSCRIPTION
  value: {AKS_SUBSCRIPTION}
- name: AKS_RG
  value: $(AKS_RG)
- name: AKS_CLUSTER_NAME
  value: $(AKS_CLUSTER_NAME)
- name: AZURE_CONTAINER_REGISTRY
  value: {AZURE_CONTAINER_REGISTRY}
- name: AGENT_COUNT
  value: '4'
- name: ORG_NAME
  value: '{AZDO_ORG_NAME}'
- name: AGENT_POOL_NAME
  value: '{AGENT_POOL_NAME}'
- group: 'VSTS-Agent-PAT'

steps:
- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    kubectlVersion: 1.13.3
    checkLatestKubectl: true

- script: |
   docker pull quay.io/10thmagnitude/aks-vsts-agent:latest
   docker tag quay.io/10thmagnitude/aks-vsts-agent $(AZURE_CONTAINER_REGISTRY)/aks-vsts-agent
  displayName: 'Pull and Tag'

- task: Docker@1
  displayName: 'Push to ACR'
  inputs:
    azureSubscriptionEndpoint: 'Hub'
    azureContainerRegistry: $(AZURE_CONTAINER_REGISTRY)
    command: 'Push an image'
    imageName: 'aks-vsts-agent'

- task: Kubernetes@1
  displayName: 'kubectl create namespace tiller'
  inputs:
    azureSubscriptionEndpoint: '$(AKS_SUBSCRIPTION)'
    azureResourceGroup: $(AKS_RG)
    kubernetesCluster: $(AKS_CLUSTER_NAME)
    command: create
    arguments: 'namespace tiller'
  continueOnError: true

- task: HelmDeploy@0
  displayName: 'helm init'
  inputs:
    azureSubscription: '$(AKS_SUBSCRIPTION)'
    azureResourceGroup: $(AKS_RG)
    kubernetesCluster: $(AKS_CLUSTER_NAME)
    command: init
    tillerNamespace: tiller

- script: |
   if [ -d "Docker/VSTS_AGENT/vsts-agent" ]; then
     cd Docker/VSTS_AGENT/vsts-agent
     git pull
   else
     git clone https://github.com/Azure/helm-vsts-agent Docker/VSTS_AGENT/vsts-agent
   fi
  displayName: 'Clone Helm Chart github.com/Azure/helm-vsts-agent'

- task: HelmDeploy@0
  displayName: 'helm delete agents'
  inputs:
    azureSubscription: '$(AKS_SUBSCRIPTION)'
    azureResourceGroup: $(AKS_RG)
    kubernetesCluster: $(AKS_CLUSTER_NAME)
    command: delete
    arguments: 'vsts-agent --purge'
    tillerNamespace: tiller
  continueOnError: true

- task: HelmDeploy@0
  displayName: 'helm install/upgrade agents'
  inputs:
    azureSubscription: '$(AKS_SUBSCRIPTION)'
    azureResourceGroup: $(AKS_RG)
    kubernetesCluster: $(AKS_CLUSTER_NAME)
    namespace: 'vsts-agent'
    command: upgrade
    chartType: FilePath
    chartPath: 'Docker/VSTS_AGENT/vsts-agent/charts/vsts-agent'
    releaseName: 'vsts-agent'
    overrideValues: 'image.repository=$(AZURE_CONTAINER_REGISTRY)/aks-vsts-agent,vstsToken=$(VSTS_AGENT_PAT_BASE64),vstsAccount=$(ORG_NAME),vstsPool="$(AGENT_POOL_NAME)",resources.requests.cpu=.5,resources.requests.memory=1Gi,resources.limits.cpu=1,resources.limits.memory=2Gi,replicas=$(AGENT_COUNT)'
    valueFile: 'Docker/VSTS_AGENT/vsts-agent/charts/vsts-agent/values.yaml'
    recreate: true
    resetValues: true
    tillerNamespace: tiller